openapi: 3.0.3
info:
  title: exo2
  version: 1.0.0
paths:
  /users:
    get:
      responses:
        200:
          description: find user
          content:
            application/json:
              schema:
                type: object
                example:
                  id: 1
                  name: "Alice"
                  email: "alice@example.com"
        400:
          description: bad types of parameters provided
          content:
            application/json:
              schema:
                type: string
                example: Bad type for provieded query parameters
    parameters:
      - name: page
        in: query
        schema:
          type: number
      - name: size
        in: query
        schema:
          type: number

