openapi: 3.0.3
info:
  title: exo6
  version: 1.0.0

paths:
  /users/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          example: 1
    get:
      responses:
        200:
          description: return user information
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/UserProfile'
        404:
          description: user not found
          content:
            application/json:
              schema:
                type: string
                example: user not found
  /users:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CreateUserProfile'
      responses:
        201:
          description: create user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserProfile'
        400:
          description: bad request
          content:
            application/json:
              schema:
                type: string
                example: bad request
components:
  schemas:
    PersonalInfo:
     properties:
        first_name:
          type: string
          example: Bozy
        last_name:
          type: string
          example: RAKOTO
        birthdate:
          type: string
          format: full-date
          example: "2025-06-26"
    Address:
      properties:
        email:
          type: string
          format: email
          example: support@example.com
        address_street:
          type: string
          example: 12d
        address_city:
          type: string
          example: Atananarivo
        address_country:
          type: string
          example: Madagascar
        address_postal_code:
          type: integer
          example: 100
    Preferences:
      properties:
        needs_newsletter:
          type: boolean
          example: false
        language:
          type: string
          enum:
            - fr
            - mg
            - eng
    UserProfile:
      allOf:
        - type: object
          properties:
            identifier:
              type: string
              format: uuid
              example: 1
        - $ref: '#/components/schemas/PersonalInfo'
        - $ref: '#/components/schemas/Address'
        - $ref: '#/components/schemas/Preferences'
    CreateUserProfile:
      allOf:
        - $ref: '#/components/schemas/PersonalInfo'
        - $ref: '#/components/schemas/Address'
        - $ref: '#/components/schemas/Preferences'



